"""add boolean

Revision ID: 1b989253add6
Revises: 8478c5f52267
Create Date: 2022-05-03 20:40:51.676253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b989253add6'
down_revision = '8478c5f52267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('moons', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'moons')
    # ### end Alembic commands ###
