"""added

Revision ID: aaa15afb4525
Revises: 1b989253add6
Create Date: 2022-05-03 21:05:12.563656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa15afb4525'
down_revision = '1b989253add6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'moons',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('planet', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('planet', 'moons',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
